# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lagoon < Formula
  desc "Lagoon's local development helper tool"
  homepage "https://github.com/uselagoon/lagoon-cli"
  version "0.21.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uselagoon/lagoon-cli/releases/download/v0.21.3/lagoon-cli-v0.21.3-darwin-amd64.tar.gz"
      sha256 "43053b8bdba3cdaa0fb0eb7c206c7bda1c08bdd44be13d5b41b1e3abfc09e916"

      def install
        bin.install "lagoon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uselagoon/lagoon-cli/releases/download/v0.21.3/lagoon-cli-v0.21.3-darwin-arm64.tar.gz"
      sha256 "c5ec8ecb0d4f8d70d083e728fa311984bd2cd5a9e55f0791eb57e88f660bb240"

      def install
        bin.install "lagoon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/uselagoon/lagoon-cli/releases/download/v0.21.3/lagoon-cli-v0.21.3-linux-amd64.tar.gz"
      sha256 "f5844ee1ef843a770e5b3760ac7a8614bec262d28c58571a098022ef73aa5938"

      def install
        bin.install "lagoon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uselagoon/lagoon-cli/releases/download/v0.21.3/lagoon-cli-v0.21.3-linux-arm64.tar.gz"
      sha256 "ed8505e5d8ebe52b72a3cef466ed4c3ab895807b961028b169b9b6b9064a97a1"

      def install
        bin.install "lagoon"
      end
    end
  end

  test do
    system "#{bin}/lagoon version"
  end
end
