# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lagoon < Formula
  desc "Lagoon's local development helper tool"
  homepage "https://github.com/uselagoon/lagoon-cli"
  version "0.18.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uselagoon/lagoon-cli/releases/download/v0.18.0/lagoon-cli-v0.18.0-darwin-amd64.tar.gz"
      sha256 "3f8f8ffc70e3e1bf3be3d24753da779c4774424ccce5674c61c5f720301ca055"

      def install
        bin.install "lagoon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uselagoon/lagoon-cli/releases/download/v0.18.0/lagoon-cli-v0.18.0-darwin-arm64.tar.gz"
      sha256 "346163ee6c341eaea8f1b19b6ba2e0fa28bf5aaf0cbd395f7f7ea8c6d5e14af6"

      def install
        bin.install "lagoon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uselagoon/lagoon-cli/releases/download/v0.18.0/lagoon-cli-v0.18.0-linux-arm64.tar.gz"
      sha256 "8398c5170d2cae38f64aeb5cbf68721c02ed8dbda62a6e1972804b24fd3d1d14"

      def install
        bin.install "lagoon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/uselagoon/lagoon-cli/releases/download/v0.18.0/lagoon-cli-v0.18.0-linux-amd64.tar.gz"
      sha256 "862a959f7112c48979b589cb3474ab164adaa69277eac19e48a8d79c8d9b86b4"

      def install
        bin.install "lagoon"
      end
    end
  end

  test do
    system "#{bin}/lagoon version"
  end
end
